### ISSUE TITLE
.The file' image_feature.npy ' in data is missing

### ISSUE THREAD

**Issue by wangyouze** [newlei/HASC#1]
hi,I found the image_feature.npy in data folder was missing when I run the HASC_model.py.
<img width="819" alt="1" src="https://user-images.githubusercontent.com/38322447/61615652-23ac9f00-ac99-11e9-89f1-3e8a15ba5905.png">
@newlei can you tell me how to get the image_feature.npy?

**Comment by newlei** [comment]
![image](https://user-images.githubusercontent.com/16752732/94223531-c9554100-ff22-11ea-8f7a-e4d71ab77c2a.png)
